package com.vsnap.vgn.application.Respository

object ApiRequestNames {

    const val Req_EmailID = "email_id"
    const val Req_OtpValidate = "otp_value"
    const val Req_password = "password"
    const val Req_Old_password = "old_password"
    const val Req_New_password = "new_password"
    const val Req_limit = "limit"
    const val Req_offset = "offset"
    const val Req_keyword = "keyword"
    const val Req_Type = "type"
    const val Req_count = "count"
    const val Req_AgentID = "agent_id"
    const val Req_CustomerID = "customer_id"
    const val Req_TemplateId = "template_id"
    const val Req_TemplateType = "template_type"
    const val Req_conference_id = "conference_id"
    const val Req_text_array = "text_array"
    const val Req_LoginId = "login_id"
    const val Req_token = "token"
    const val from_date = "from_date"
    const val to_date = "to_date"
    const val Req_CustomerName = "customer_name"
    const val Req_CustomerEmail = "customer_email"
    const val Req_CusMobilenumber = "customer_mobile"
    const val Req_CusAlternateMobilenumber = "customer_alternate_mobile"
    const val Req_CusPinCode = "customer_pincode"
    const val Req_CusArea = "customer_area"
    const val Req_CusFollowUpdate = "follow_up_date"
    const val Req_CusFollowUptime = "follow_up_time"
    const val Req_ActionTaken = "action_taken"
    const val Req_AgentNumber = "agent_number"
    const val Req_CustomerNumber = "customer_number"
    const val Req_OldConferenceID = "old_conference_id"
    const val Req_OrganisationID = "organisation_id"
    const val Req_ProjectID = "project_id"
    const val Req_DeviceType = "device_type"
    const val Req_DeviceToken = "device_token"
    const val Req_VersionCode = "version_code"
    const val Req_FromDate = "fromdate"
    const val Req_ToDate = "todate"
    const val Req_MemberID = "member_id"
    const val Req_CallAvailability = "call_availability"
    const val Req_Remarks = "remarks"
    const val Req_documentid = "document_id"
    const val Req_opentext = "Open_text"
    const val customer_type = "customer_type"

}